substitutions:
  _IMAGE: ""
  _VERSION: ""
  _COMMIT_SHA: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_IMAGE}"
      - "--build-arg"
      - "VERSION=${_VERSION}"
      - "--build-arg"
      - "COMMIT_SHA=${_COMMIT_SHA}"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_IMAGE}"

images:
  - "${_IMAGE}"